os: linux
arch:
- amd64
- ppc64le
language: python
python:
- "2.7"
- "3.4"
- "3.8"
- "pypy"
- "pypy3"
jobs:
  exclude:
   - arch : ppc64le
     python : pypy
   - arch : ppc64le
     python : pypy3	 
addons:
  apt:
    packages:
    - libusb-1.0-0
    - libudev-dev
    - doxygen
    - bash
    sources:
    - ubuntu-toolchain-r-test
# Note: "doxygen" actually comes from "apt-get build-deps libusb-1.0-0", but
# there is no direct travis equivalent.
install: pip install .
# v1.0.19 is Debian jessie (oldoldstable)
# v1.0.22 is Debian buster (stable)
script: ./runTestLibusb.sh https://github.com/libusb/libusb.git libusb.git master v1.0.19 v1.0.22
